package domain

import (
	"slices"
	"strings"
	"time"
)

// Device is one installation of the Desktop Agent.
//
// The ID is generated by the agent before registration, which is why it is a
// client-supplied ULID rather than a database sequence.
type Device struct {
	ID           string
	UserID       string
	Name         string
	Platform     string // "windows/amd64"
	AgentVersion string

	// Capabilities lists coding agents actually INSTALLED on that machine, taken
	// from the AUTH handshake. Not what the binary supports: a build supporting
	// five adapters on a machine with one installed has one capability. This is
	// what stops a prompt being dispatched to a device that cannot service it.
	Capabilities []string

	// TokenHash is a SHA-256 of the device token. The plaintext is returned once
	// at registration and never stored, so a database dump yields no working
	// credentials.
	TokenHash      string
	TokenExpiresAt time.Time

	LastSeenAt *time.Time

	// RevokedAt is deliberately separate from DeletedAt. Revoking a compromised
	// machine's access is not the same act as removing it from the user's list,
	// and conflating them makes "revoke but keep the history" impossible.
	RevokedAt *time.Time

	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

// Validate checks device invariants.
func (d *Device) Validate() error {
	if d.UserID == "" {
		return Invalid("user_id", "must be set")
	}
	if strings.TrimSpace(d.Name) == "" {
		return Invalid("name", "must not be empty")
	}
	if len(d.Name) > 128 {
		return Invalid("name", "must be 128 characters or fewer")
	}
	if strings.TrimSpace(d.Platform) == "" {
		return Invalid("platform", "must not be empty")
	}
	return nil
}

// Revoked reports whether the device's credentials have been revoked.
func (d *Device) Revoked() bool { return d.RevokedAt != nil }

// Deleted reports whether the device was soft-deleted.
func (d *Device) Deleted() bool { return d.DeletedAt != nil }

// TokenValid reports whether the device token is still usable at now.
//
// Checks revocation, deletion, and expiry together, so no caller can accidentally
// verify only one of the three. Getting that wrong would let a revoked device
// keep connecting.
func (d *Device) TokenValid(now time.Time) bool {
	if d.Revoked() || d.Deleted() {
		return false
	}
	return now.Before(d.TokenExpiresAt)
}

// Supports reports whether the named coding agent is installed on this device.
func (d *Device) Supports(adapter string) bool {
	return slices.Contains(d.Capabilities, adapter)
}

// Online reports whether the device was seen within the staleness window.
//
// This is a fallback for when Redis presence is unavailable. Presence is
// authoritative when it can be reached; deriving liveness from a timestamp is
// less accurate because a device that crashed still has a recent LastSeenAt.
func (d *Device) Online(now time.Time, staleAfter time.Duration) bool {
	if d.LastSeenAt == nil || d.Revoked() || d.Deleted() {
		return false
	}
	return now.Sub(*d.LastSeenAt) <= staleAfter
}

// AgentStatus is the latest resource snapshot reported by a device.
//
// One row per device, updated in place rather than appended. A 10-second
// heartbeat appended forever would make this the largest table in the database
// in exchange for history nobody asked for.
type AgentStatus struct {
	DeviceID      string
	State         string // mirrors protocol.AgentState
	Adapter       string
	Repository    string
	CurrentTask   string
	CPUPercent    float64
	MemoryBytes   uint64
	QueuedPrompts int
	SessionID     string
	ReportedAt    time.Time
	UpdatedAt     time.Time
}
